using System.ComponentModel;

namespace Rocket.Core;

/// <summary>
/// Every string the app shows, in Persian and English. Bind with
/// <c>{Binding [key], Source={x:Static core:Loc.I}}</c>; switching language re-raises them all.
/// </summary>
public sealed class Loc : INotifyPropertyChanged
{
    public static Loc I { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;
    public event Action? LanguageChanged;

    public string Lang { get; private set; } = "fa";
    public bool IsFa => Lang == "fa";

    public void Set(string lang)
    {
        Lang = lang == "en" ? "en" : "fa";
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsFa)));
        LanguageChanged?.Invoke();
    }

    public string this[string key]
    {
        get
        {
            if (S.TryGetValue(key, out var v)) return IsFa ? v.Fa : v.En;
            return key.StartsWith("d.") ? "" : key;
        }
    }

    public string F(string key, params object[] args)
    {
        try { return string.Format(this[key], args); } catch { return this[key]; }
    }

    private static readonly Dictionary<string, (string En, string Fa)> S = new()
    {
        ["app.tagline"] = ("Free the space your tools left behind", "فضایی که ابزارها پشت سر گذاشتن رو پس بگیر"),

        ["nav.clean"] = ("Quick clean", "پاک‌سازی سریع"),
        ["nav.clean.hint"] = ("Caches, temp, leftovers", "کش، فایل موقت، باقی‌مانده‌ها"),
        ["nav.projects"] = ("Projects", "پروژه‌ها"),
        ["nav.projects.hint"] = ("node_modules, builds", "node_modules و خروجی بیلد"),
        ["nav.models"] = ("AI models", "مدل‌های هوش مصنوعی"),
        ["nav.models.hint"] = ("Hugging Face, Ollama…", "Hugging Face، Ollama و …"),
        ["nav.map"] = ("Space map", "نقشه‌ی فضا"),
        ["nav.map.hint"] = ("What fills each drive", "چی درایو رو پر کرده"),
        ["nav.overview"] = ("Overview", "نمای کلی"),
        ["nav.overview.hint"] = ("This PC at a glance", "وضعیت این کامپیوتر در یک نگاه"),
        ["nav.g.space"] = ("FREE SPACE", "آزادسازی فضا"),
        ["nav.g.speed"] = ("SPEED", "سرعت"),
        ["nav.g.system"] = ("SYSTEM", "سیستم"),
        ["nav.programs"] = ("Programs", "برنامه‌های نصب‌شده"),
        ["nav.programs.hint"] = ("Uninstall, sweep leftovers", "حذف نصب و پاک‌کردن باقی‌مانده‌ها"),
        ["nav.startup"] = ("Startup", "برنامه‌های استارتاپ"),
        ["nav.startup.hint"] = ("What runs at sign-in", "چیزهایی که با ویندوز اجرا می‌شن"),
        ["nav.processes"] = ("Processes", "پردازش‌ها"),
        ["nav.processes.hint"] = ("CPU, memory, end task", "CPU، حافظه، بستن برنامه"),
        ["nav.tune"] = ("Tune-up", "بهینه‌سازی"),
        ["nav.tune.hint"] = ("CPU, services, antivirus", "CPU، سرویس‌ها، آنتی‌ویروس"),
        ["nav.system"] = ("This PC", "این کامپیوتر"),
        ["nav.system.hint"] = ("Specs and upgrades", "مشخصات و ارتقا"),
        ["drive.freeshort"] = ("{0} free", "{0} آزاد"),
        ["nav.history"] = ("History", "تاریخچه"),
        ["nav.history.hint"] = ("What was freed", "چقدر آزاد شد"),
        ["nav.drives"] = ("DRIVES", "درایوها"),
        ["nav.tools"] = ("TOOLS", "ابزارها"),

        ["drive.free"] = ("{0} free of {1}", "{0} آزاد از {1}"),
        ["drive.full"] = ("Almost full", "تقریباً پر"),

        ["common.reveal"] = ("Show in Explorer", "نمایش در Explorer"),
        ["common.rescan"] = ("Scan again", "اسکن دوباره"),
        ["common.scan"] = ("Scan", "اسکن"),
        ["common.cancel"] = ("Cancel", "انصراف"),
        ["common.close"] = ("Close", "بستن"),
        ["common.selectall"] = ("Select all", "انتخاب همه"),
        ["common.selectnone"] = ("Select none", "هیچ‌کدوم"),
        ["common.selected"] = ("selected", "انتخاب شده"),
        ["common.clean"] = ("Clean {0}", "پاک‌سازی {0}"),
        ["common.nothing"] = ("Nothing selected", "چیزی انتخاب نشده"),
        ["common.found"] = ("{0} found · {1} items", "{0} پیدا شد · {1} مورد"),
        ["common.scanning"] = ("Scanning…", "در حال اسکن…"),
        ["common.measuring"] = ("Measuring {0} of {1}…", "اندازه‌گیری {0} از {1}…"),
        ["common.ready"] = ("Scanned in {0}", "اسکن در {0}"),
        ["common.canfree"] = ("You can free", "قابل آزادسازی"),

        ["badge.review"] = ("Check first", "اول بررسی کن"),
        ["badge.admin"] = ("Admin", "ادمین"),
        ["admin.banner"] = ("{0} more is in Windows folders that need administrator rights.", "{0} دیگه توی پوشه‌های ویندوز هست که دسترسی ادمین می‌خواد."),
        ["admin.btn"] = ("Restart as administrator", "اجرای دوباره با دسترسی ادمین"),

        ["clean.title"] = ("Quick clean", "پاک‌سازی سریع"),
        ["clean.sub"] = ("Caches, temporary files and leftovers that nothing needs. Everything ticked is safe to delete; rows marked “check first” are yours to decide.",
            "کش‌ها، فایل‌های موقت و باقی‌مانده‌هایی که هیچ برنامه‌ای لازمشون نداره. هر چیزی که تیک خورده بی‌خطره؛ ردیف‌های «اول بررسی کن» تصمیمش با خودته."),

        ["g.system"] = ("Windows", "ویندوز"),
        ["g.system.hint"] = ("Temp files, update downloads, crash reports", "فایل‌های موقت، دانلود آپدیت‌ها، گزارش خطاها"),
        ["g.dev"] = ("Developer caches", "کش ابزارهای برنامه‌نویسی"),
        ["g.dev.hint"] = ("Package managers download these again when they need them", "پکیج منیجرها هر وقت لازم داشته باشن دوباره دانلودشون می‌کنن"),
        ["g.editors"] = ("Code editors", "ویرایشگرهای کد"),
        ["g.editors.hint"] = ("VS Code, Cursor, Windsurf, Kiro… caches and replaced extensions", "کش VS Code، Cursor، Windsurf، Kiro و نسخه‌های قدیمی افزونه‌ها"),
        ["g.ai"] = ("AI tools", "ابزارهای هوش مصنوعی"),
        ["g.ai.hint"] = ("Logs and download caches of AI tools — models are on their own page", "لاگ‌ها و کش دانلود ابزارهای هوش مصنوعی — مدل‌ها صفحه‌ی خودشون رو دارن"),
        ["g.apps"] = ("Browsers & apps", "مرورگرها و برنامه‌ها"),
        ["g.apps.hint"] = ("Web caches, old app versions, downloaded updates", "کش وب، نسخه‌های قدیمی برنامه‌ها، آپدیت‌های دانلودشده"),
        ["g.files"] = ("Forgotten files", "فایل‌های فراموش‌شده"),
        ["g.files.hint"] = ("Things you downloaded once — have a look before deleting", "چیزهایی که یه بار دانلود کردی — قبل از حذف نگاه کن"),

        ["t.temp"] = ("Temporary files", "فایل‌های موقت"),
        ["d.temp"] = ("Your Temp folder, files older than a day", "پوشه‌ی Temp خودت، فایل‌های قدیمی‌تر از یک روز"),
        ["t.wintemp"] = ("Windows temporary files", "فایل‌های موقت ویندوز"),
        ["d.wintemp"] = ("C:\\Windows\\Temp, older than a day", "C:\\Windows\\Temp، قدیمی‌تر از یک روز"),
        ["t.recycle"] = ("Recycle Bin", "سطل بازیافت"),
        ["d.recycle"] = ("Files you already deleted, on every drive", "فایل‌هایی که قبلاً حذف کردی، روی همه‌ی درایوها"),
        ["t.wu"] = ("Windows Update downloads", "دانلودهای Windows Update"),
        ["d.wu"] = ("Installed updates' setup files", "فایل‌های نصب آپدیت‌هایی که نصب شدن"),
        ["t.delivery"] = ("Delivery Optimization cache", "کش Delivery Optimization"),
        ["d.delivery"] = ("Update pieces kept to share with other PCs", "تکه‌های آپدیت که برای اشتراک با بقیه‌ی کامپیوترها نگه داشته شده"),
        ["t.wer"] = ("Error reports and crash dumps", "گزارش خطا و crash dump ها"),
        ["d.wer"] = ("Reports Windows already sent or never will", "گزارش‌هایی که ویندوز فرستاده یا هیچ‌وقت نمی‌فرسته"),
        ["t.wersys"] = ("System error reports", "گزارش خطاهای سیستم"),
        ["d.wersys"] = ("System-wide reports, minidumps, kernel reports", "گزارش‌های سراسری، minidump و گزارش‌های کرنل"),
        ["t.memdump"] = ("Memory dump", "Memory dump"),
        ["d.memdump"] = ("Written after a blue screen; only useful to debug it", "بعد از صفحه‌ی آبی نوشته می‌شه؛ فقط برای دیباگ به درد می‌خوره"),
        ["t.shader"] = ("Graphics shader cache", "کش شیدر گرافیک"),
        ["d.shader"] = ("DirectX, NVIDIA, AMD and Intel rebuild it", "DirectX و درایور کارت گرافیک دوباره می‌سازنش"),
        ["t.inet"] = ("Internet cache", "کش اینترنت"),
        ["d.inet"] = ("The old Windows web cache", "کش وب قدیمی ویندوز"),
        ["t.cbs"] = ("Windows logs", "لاگ‌های ویندوز"),
        ["d.cbs"] = ("Component, DISM and update logs older than three days", "لاگ‌های CBS، DISM و آپدیت قدیمی‌تر از سه روز"),
        ["t.oldwin"] = ("Previous Windows installation", "نصب قبلی ویندوز"),
        ["d.oldwin"] = ("Windows.old and upgrade leftovers — deleting them removes the way back", "Windows.old و باقی‌مانده‌ی ارتقا — با حذفش دیگه نمی‌شه برگشت"),
        ["t.hiber"] = ("Hibernation file", "فایل Hibernate"),
        ["d.hiber"] = ("Turns hibernate and fast startup off to remove hiberfil.sys", "Hibernate و Fast startup رو خاموش می‌کنه تا hiberfil.sys حذف بشه"),
        ["t.winsxs"] = ("Superseded Windows components", "کامپوننت‌های جایگزین‌شده‌ی ویندوز"),
        ["d.winsxs"] = ("DISM component cleanup; takes several minutes, size known only after", "پاک‌سازی DISM؛ چند دقیقه طول می‌کشه و حجمش بعد از اجرا معلوم می‌شه"),

        ["t.npm"] = ("npm cache", "کش npm"),
        ["d.npm"] = ("Every package npm ever downloaded", "هر پکیجی که npm تا حالا دانلود کرده"),
        ["t.yarn"] = ("Yarn cache", "کش Yarn"),
        ["t.pnpm"] = ("pnpm store", "استور pnpm"),
        ["d.pnpm"] = ("Shared with projects through hard links — frees less than it shows if projects still use it", "از طریق hard link با پروژه‌ها مشترکه — اگه پروژه‌ها هنوز استفاده کنن کمتر از این آزاد می‌شه"),
        ["t.bun"] = ("Bun cache", "کش Bun"),
        ["t.nodegyp"] = ("node-gyp headers", "هدرهای node-gyp"),
        ["t.nodecli"] = ("Node tool caches", "کش ابزارهای Node"),
        ["d.nodecli"] = ("next, swc, prisma, vitest and other CLIs", "next، swc، prisma، vitest و بقیه‌ی CLI ها"),
        ["t.pip"] = ("pip cache", "کش pip"),
        ["t.uv"] = ("uv cache", "کش uv"),
        ["t.poetry"] = ("Poetry cache", "کش Poetry"),
        ["t.conda"] = ("Conda package cache", "کش پکیج‌های Conda"),
        ["t.nugethttp"] = ("NuGet download cache", "کش دانلود NuGet"),
        ["t.nuget"] = ("NuGet packages", "پکیج‌های NuGet"),
        ["d.nuget"] = ("Restored again on the next build", "در بیلد بعدی دوباره دانلود می‌شن"),
        ["t.gradle"] = ("Gradle caches", "کش Gradle"),
        ["d.gradle"] = ("Dependencies and Gradle versions; the next Android build downloads them again", "وابستگی‌ها و نسخه‌های Gradle؛ بیلد بعدی اندروید دوباره دانلودشون می‌کنه"),
        ["t.gradled"] = ("Gradle daemon logs", "لاگ‌های Gradle daemon"),
        ["t.maven"] = ("Maven repository", "مخزن Maven"),
        ["t.cargo"] = ("Cargo registry", "رجیستری Cargo"),
        ["t.gobuild"] = ("Go build cache", "کش بیلد Go"),
        ["t.gomod"] = ("Go module cache", "کش ماژول‌های Go"),
        ["t.electron"] = ("Electron downloads", "دانلودهای Electron"),
        ["d.electron"] = ("Electron and electron-builder binaries kept after builds", "باینری‌های Electron و electron-builder که بعد از بیلد مونده"),
        ["t.browsers"] = ("Test browsers", "مرورگرهای تست"),
        ["d.browsers"] = ("Playwright, Puppeteer, Cypress and Selenium downloads", "دانلودهای Playwright، Puppeteer، Cypress و Selenium"),
        ["t.android"] = ("Android build caches", "کش بیلد اندروید"),
        ["t.composer"] = ("Composer cache", "کش Composer"),
        ["t.vs"] = ("Visual Studio component cache", "کش کامپوننت Visual Studio"),
        ["t.vspkg"] = ("Installer package cache", "کش پکیج‌های نصب"),
        ["d.vspkg"] = ("Kept by installers for repair; usually safe", "نصب‌کننده‌ها برای تعمیر نگه می‌دارن؛ معمولاً بی‌خطره"),
        ["t.javacrash"] = ("Java crash logs", "لاگ کرش جاوا"),
        ["d.javacrash"] = ("hs_err_pid files in your home folder", "فایل‌های hs_err_pid توی پوشه‌ی کاربر"),
        ["t.claudetmp"] = ("Claude config leftovers", "باقی‌مانده‌های تنظیمات Claude"),
        ["d.claudetmp"] = (".claude.json.tmp files left by interrupted writes", "فایل‌های .claude.json.tmp که از نوشتن‌های نیمه‌کاره مونده"),
        ["t.claudever"] = ("Old Claude Code versions", "نسخه‌های قدیمی Claude Code"),
        ["d.claudever"] = ("The newest one is kept", "جدیدترین نسخه نگه داشته می‌شه"),
        ["t.claudestage"] = ("Claude update staging", "فایل‌های موقت آپدیت Claude"),
        ["t.jbcache"] = ("JetBrains caches and logs", "کش و لاگ JetBrains"),
        ["d.jbcache"] = ("Indexes are rebuilt when a project opens", "ایندکس‌ها با باز شدن پروژه دوباره ساخته می‌شن"),
        ["t.jbold"] = ("Old JetBrains IDE versions", "نسخه‌های قدیمی IDE های JetBrains"),
        ["d.jbold"] = ("Settings and caches of versions you upgraded from", "تنظیمات و کش نسخه‌هایی که ازشون ارتقا دادی"),

        ["t.sdkndk"] = ("Old Android NDK versions", "نسخه‌های قدیمی Android NDK"),
        ["d.sdkndk"] = ("The newest is kept; a project pinned to an older one downloads it again", "جدیدترین می‌مونه؛ پروژه‌ای که نسخه‌ی قدیمی‌تر بخواد دوباره دانلودش می‌کنه"),
        ["t.sdkbt"] = ("Old build-tools and CMake", "build-tools و CMake قدیمی"),
        ["d.sdkbt"] = ("The two newest build-tools and the newest CMake are kept", "دو نسخه‌ی آخر build-tools و آخرین CMake می‌مونن"),
        ["t.sdkplat"] = ("Old Android platforms", "پلتفرم‌های قدیمی اندروید"),
        ["d.sdkplat"] = ("The three newest API levels are kept", "سه API level آخر می‌مونن"),
        ["t.sdkimg"] = ("Emulator system images", "ایمیج‌های امولاتور"),
        ["d.sdkimg"] = ("Your emulators need them; delete the ones you no longer run", "امولاتورها لازمشون دارن؛ اونایی که دیگه اجرا نمی‌کنی رو پاک کن"),
        ["t.sdktmp"] = ("Android SDK leftovers", "باقی‌مانده‌های Android SDK"),
        ["d.sdktmp"] = ("Interrupted downloads and the platform-tools backup", "دانلودهای نیمه‌کاره و بکاپ platform-tools"),
        ["t.editorcache"] = ("cache", "کش"),
        ["d.code"] = ("Compiled code cache, downloaded extension files, logs", "کش کد کامپایل‌شده، فایل‌های دانلودشده‌ی افزونه، لاگ‌ها"),
        ["t.oldext"] = ("Replaced extension versions ({0})", "نسخه‌های قدیمی افزونه‌ها ({0})"),
        ["d.ext"] = ("Only the newest version of each extension is loaded", "فقط جدیدترین نسخه‌ی هر افزونه استفاده می‌شه"),

        ["t.hfxet"] = ("Hugging Face download cache", "کش دانلود Hugging Face"),
        ["d.hfxet"] = ("Chunks kept to resume downloads — not the models", "تکه‌هایی برای ادامه‌ی دانلود — خود مدل‌ها نه"),
        ["t.codexrt"] = ("Codex runtimes", "ران‌تایم‌های Codex"),
        ["t.opencode"] = ("opencode cache", "کش opencode"),
        ["t.ailogs"] = ("AI tool logs", "لاگ ابزارهای هوش مصنوعی"),
        ["d.ailogs"] = ("Claude, Codex and Gemini logs older than three days", "لاگ‌های Claude، Codex و Gemini قدیمی‌تر از سه روز"),

        ["t.mediacache"] = ("media cache", "کش رسانه"),
        ["d.telegram"] = ("Photos and videos from chats; downloaded again when you open them", "عکس و ویدیوی چت‌ها؛ با باز کردن دوباره دانلود می‌شن"),
        ["t.spotify"] = ("Spotify cache", "کش Spotify"),
        ["t.steam"] = ("Steam web cache", "کش وب Steam"),
        ["t.browsercache"] = ("cache", "کش"),
        ["d.firefox"] = ("Web cache, start-up cache and thumbnails", "کش وب، کش شروع و تصاویر کوچک"),
        ["t.appcache"] = ("cache", "کش"),
        ["d.chromium"] = ("Web, code and GPU caches — sign-ins and settings stay", "کش وب، کد و GPU — لاگین‌ها و تنظیمات می‌مونن"),
        ["t.updaters"] = ("Downloaded app updates", "آپدیت‌های دانلودشده‌ی برنامه‌ها"),
        ["d.updaters"] = ("Installers apps kept after updating themselves", "نصب‌کننده‌هایی که برنامه‌ها بعد از آپدیت نگه داشتن"),
        ["t.squirrel"] = ("Old app versions", "نسخه‌های قدیمی برنامه‌ها"),
        ["d.squirrel"] = ("Discord, Slack, GitHub Desktop… keep the previous version next to the current one", "Discord، Slack، GitHub Desktop و … نسخه‌ی قبلی رو کنار نسخه‌ی فعلی نگه می‌دارن"),

        ["t.installers"] = ("Old installers and archives", "نصب‌کننده‌ها و فایل‌های فشرده‌ی قدیمی"),
        ["d.installers"] = ("In Downloads, untouched for 30 days", "توی Downloads، ۳۰ روزه دست نخورده"),
        ["t.tgdl"] = ("Telegram downloads", "دانلودهای تلگرام"),
        ["d.tgdl"] = ("Files you saved from Telegram", "فایل‌هایی که از تلگرام ذخیره کردی"),
        ["t.thumbs"] = ("Thumbnail cache", "کش تصاویر کوچک"),

        ["idle.today"] = ("Active today", "امروز فعال"),
        ["idle.days"] = ("Idle {0} days", "{0} روز بدون تغییر"),

        ["projects.title"] = ("Projects", "پروژه‌ها"),
        ["projects.sub"] = ("What installs and builds leave inside your projects. All of it comes back with npm install or the next build — so the projects you haven’t touched in a while are ticked.",
            "چیزهایی که نصب و بیلد داخل پروژه‌ها جا می‌ذارن. همه‌ش با npm install یا بیلد بعدی برمی‌گرده — برای همین پروژه‌هایی که مدتیه دست نخوردن تیک خوردن."),
        ["projects.walking"] = ("Looking through {0}…", "در حال گشتن {0}…"),
        ["projects.idle"] = ("Tick projects idle for", "تیک پروژه‌هایی که بیکار بودن به مدت"),
        ["projects.days"] = ("{0} days", "{0} روز"),
        ["projects.caches"] = ("Build caches only", "فقط کش‌های بیلد"),
        ["projects.where"] = ("Looks in: {0}", "محل جستجو: {0}"),
        ["projects.add"] = ("Add folder", "افزودن پوشه"),
        ["kind.node_modules"] = ("node_modules", "node_modules"),
        ["kind.cache"] = ("build cache", "کش بیلد"),
        ["kind.output"] = ("build output", "خروجی بیلد"),
        ["kind.pycache"] = ("Python cache", "کش پایتون"),
        ["kind.venv"] = ("virtualenv", "virtualenv"),
        ["projects.folders"] = ("{0} folders", "{0} پوشه"),

        ["models.title"] = ("AI models", "مدل‌های هوش مصنوعی"),
        ["models.sub"] = ("Every model downloaded to this PC, biggest first. None is ticked — pick the ones you no longer use. Downloading one again takes time.",
            "همه‌ی مدل‌هایی که روی این کامپیوتر دانلود شدن، بزرگ‌ترها اول. هیچ‌کدوم تیک نخورده — اونایی که دیگه استفاده نمی‌کنی رو انتخاب کن. دانلود دوباره وقت می‌بره."),
        ["models.file"] = ("Model file", "فایل مدل"),
        ["models.none"] = ("No downloaded models found.", "مدل دانلودشده‌ای پیدا نشد."),
        ["models.loose"] = ("Model files on your drives are found by the Projects scan.", "فایل‌های مدل روی درایوها با اسکن پروژه‌ها پیدا می‌شن."),

        ["map.title"] = ("Space map", "نقشه‌ی فضا"),
        ["map.sub"] = ("Everything on a drive, biggest first. Double-click a folder to open it.", "همه‌چیز روی درایو، بزرگ‌ترها اول. روی پوشه دوبار کلیک کن تا بازش کنی."),
        ["map.analyze"] = ("Map {0}", "نقشه‌ی {0}"),
        ["map.files"] = ("{0} files", "{0} فایل"),
        ["map.up"] = ("Up", "بالا"),
        ["map.delete"] = ("Delete", "حذف"),
        ["map.walking"] = ("{0} files · {1}", "{0} فایل · {1}"),
        ["map.hidden"] = ("{0} the scan could not read (system files, other users)", "{0} که اسکن نتونست بخونه (فایل‌های سیستمی، کاربرهای دیگه)"),
        ["map.pick"] = ("Pick a drive to map", "یه درایو انتخاب کن"),
        ["map.protected"] = ("This is part of Windows or an installed program. Uninstall the program instead, or use Quick clean for Windows files.",
            "این بخشی از ویندوز یا یه برنامه‌ی نصب‌شده‌ست. برنامه رو حذف نصب کن، یا برای فایل‌های ویندوز از پاک‌سازی سریع استفاده کن."),
        ["map.done"] = ("{0} files in {1}", "{0} فایل در {1}"),

        ["history.title"] = ("History", "تاریخچه"),
        ["history.sub"] = ("Every clean-up, and what it gave back.", "هر پاک‌سازی و فضایی که آزاد کرد."),
        ["history.none"] = ("Nothing cleaned yet.", "هنوز چیزی پاک نشده."),
        ["history.total"] = ("{0} freed in total", "در مجموع {0} آزاد شده"),

        ["confirm.title"] = ("Delete for good?", "برای همیشه حذف بشه؟"),
        ["confirm.body"] = ("{0} items, {1}. They skip the Recycle Bin — that is what frees the space.",
            "{0} مورد، {1}. از سطل بازیافت رد می‌شن — فضا همین‌طوری آزاد می‌شه."),
        ["confirm.review"] = ("{0} of them are marked “check first”.", "{0} موردش «اول بررسی کن» هست."),
        ["confirm.go"] = ("Delete", "حذف کن"),
        ["confirm.map"] = ("Delete “{0}” ({1}) for good? This is not a cache — make sure you no longer need it.",
            "«{0}» ({1}) برای همیشه حذف بشه؟ این کش نیست — مطمئن شو دیگه لازمش نداری."),

        ["job.background"] = ("Continue in background", "ادامه در پس‌زمینه"),
        ["job.open"] = ("Show the clean-up", "نمایش پاک‌سازی"),
        ["job.running"] = ("{0} freed", "{0} آزاد شد"),
        ["job.done"] = ("Freed {0}", "{0} آزاد شد ✓"),
        ["job.busy"] = ("Cleaning…", "در حال پاک‌سازی…"),
        ["job.quit"] = ("A clean-up is still running. Stop it and close Rocket?", "پاک‌سازی هنوز در حال اجراست. متوقفش کنم و Rocket بسته بشه؟"),
        ["admin.refused"] = ("The administrator prompt was declined — nothing changed.", "درخواست دسترسی ادمین رد شد — چیزی تغییر نکرد."),

        ["startup.title"] = ("Startup programs", "برنامه‌های استارتاپ"),
        ["startup.sub"] = ("Everything Windows opens when you sign in. Each one keeps a slice of the CPU and memory from the first second. Turning one off doesn't uninstall it — it just waits until you open it yourself.",
            "هر چیزی که ویندوز با ورود شما اجرا می‌کنه. هر کدوم از همون ثانیه‌ی اول یه تیکه از CPU و حافظه رو برمی‌داره. خاموش کردنش برنامه رو حذف نمی‌کنه — فقط صبر می‌کنه تا خودت بازش کنی."),
        ["startup.count"] = ("{0} of {1} start with Windows", "{0} از {1} با ویندوز اجرا می‌شن"),
        ["startup.hint"] = ("Same switch Task Manager uses, so the two always agree. Nothing is deleted.", "همون کلیدی که Task Manager استفاده می‌کنه، پس همیشه یکی‌ان. چیزی حذف نمی‌شه."),
        ["startup.allusers"] = ("All users", "همه‌ی کاربرها"),
        ["startup.you"] = ("You", "شما"),
        ["startup.running"] = ("Running · {0}", "در حال اجرا · {0}"),
        ["startup.needadmin"] = ("Changing this one asks for administrator rights", "تغییر این یکی دسترسی ادمین می‌خواد"),
        ["startup.log.on"] = ("Startup: {0} turned on", "استارتاپ: {0} روشن شد"),
        ["startup.log.off"] = ("Startup: {0} turned off", "استارتاپ: {0} خاموش شد"),

        ["tune.title"] = ("Tune-up", "بهینه‌سازی"),
        ["tune.sub"] = ("Let the processor run at the speed you paid for, stop the services that work against a build machine, and keep the antivirus out of your caches. Every change can be put back with one click.",
            "بذار پردازنده با سرعتی که براش پول دادی کار کنه، سرویس‌هایی که به ضرر یه سیستم برنامه‌نویسی‌ان رو خاموش کن و آنتی‌ویروس رو از کش‌ها دور نگه دار. هر تغییری با یه کلیک برمی‌گرده."),
        ["tune.clock"] = ("Clock now", "سرعت الان"),
        ["tune.ofrated"] = ("{0}% of the rated {1} GHz", "{0}٪ از {1} گیگاهرتز اسمی"),
        ["tune.load"] = ("Load", "بار"),
        ["tune.plan"] = ("Power plan", "طرح انرژی"),
        ["tune.cpu"] = ("Processor", "پردازنده"),
        ["tune.throttled"] = ("The CPU is busy but held to {0}% of its clock. The tweaks below lift that limit.", "CPU مشغوله ولی روی {0}٪ سرعتش نگه داشته شده. تنظیمات پایین این محدودیت رو برمی‌دارن."),
        ["tune.throttled.battery"] = ("On battery the CPU is held to {0}% of its clock — plug in, or apply the tweaks below.", "روی باتری CPU روی {0}٪ سرعتش نگه داشته شده — به برق وصل کن یا تنظیمات پایین رو اعمال کن."),
        ["tune.capped"] = ("Maximum processor state is capped at {0}%.", "حداکثر توان پردازنده روی {0}٪ محدود شده."),

        ["tw.section"] = ("CPU & power", "CPU و انرژی"),
        ["tw.note"] = ("The original settings are saved before the first change, so Restore puts everything back.", "قبل از اولین تغییر تنظیمات اصلی ذخیره می‌شن، پس «بازگردانی» همه‌چیز رو برمی‌گردونه."),
        ["tw.backup"] = ("Original settings saved {0} — Restore puts them back.", "تنظیمات اصلی در {0} ذخیره شده — «بازگردانی» برشون می‌گردونه."),
        ["tw.apply"] = ("Apply {0} changes", "اعمال {0} تغییر"),
        ["tw.allset"] = ("All set", "همه اعمال شده"),
        ["tw.on"] = ("On ✓", "فعال ✓"),
        ["tw.unknown"] = ("Unknown", "نامشخص"),
        ["tw.restore"] = ("Restore original", "بازگردانی تنظیمات اصلی"),
        ["tw.restore.q"] = ("Put the power plan, processor settings, power mode, foreground priority and services back the way they were before Rocket changed them?",
            "طرح انرژی، تنظیمات پردازنده، حالت انرژی، اولویت برنامه‌ی جلو و سرویس‌ها به حالت قبل از تغییرات Rocket برگردن؟"),
        ["tw.restored"] = ("Original CPU and power settings restored", "تنظیمات اصلی CPU و انرژی برگشت"),
        ["tw.applied"] = ("Applied. The processor can now run at full speed.", "اعمال شد. پردازنده حالا می‌تونه با تمام سرعت کار کنه."),
        ["tw.log"] = ("CPU & power tweaks applied", "تنظیمات CPU و انرژی اعمال شد"),
        ["tw.notrecorded"] = ("Windows did not record the change.", "ویندوز تغییر رو ثبت نکرد."),
        ["tw.plan"] = ("High performance power plan", "طرح انرژی High performance"),
        ["tw.plan.d"] = ("The processor stops dropping its clock to save power while you work.", "پردازنده برای صرفه‌جویی انرژی وسط کار سرعتش رو پایین نمیاره."),
        ["tw.plan.laptop"] = ("Uses more battery.", "باتری بیشتری مصرف می‌کنه."),
        ["tw.max"] = ("Maximum processor state 100%", "حداکثر توان پردازنده ۱۰۰٪"),
        ["tw.max.d"] = ("Some plans cap the CPU below its full speed; this takes the cap off.", "بعضی طرح‌ها CPU رو زیر سرعت کاملش محدود می‌کنن؛ این محدودیت رو برمی‌داره."),
        ["tw.boost"] = ("Turbo boost: aggressive", "توربو بوست: حداکثر"),
        ["tw.boost.d"] = ("Lets the chip climb above its base clock as soon as there is work.", "اجازه می‌ده به محض اینکه کار هست، چیپ از سرعت پایه بالاتر بره."),
        ["tw.cores"] = ("No core parking", "بدون پارک هسته‌ها"),
        ["tw.cores.d"] = ("Keeps every core awake, so a build doesn't wait for cores to wake up.", "همه‌ی هسته‌ها بیدار می‌مونن، تا بیلد منتظر بیدار شدن هسته‌ها نمونه."),
        ["tw.min"] = ("Minimum processor state 100% on power", "حداقل توان پردازنده ۱۰۰٪ روی برق"),
        ["tw.min.d"] = ("The CPU never idles down while plugged in. More heat and power; rarely needed.", "روی برق CPU هیچ‌وقت پایین نمیاد. گرما و مصرف بیشتر؛ به ندرت لازمه."),
        ["tw.min.laptop"] = ("Only applies while plugged in.", "فقط وقتی به برق وصله اعمال می‌شه."),
        ["tw.cooling"] = ("Active cooling", "خنک‌سازی فعال"),
        ["tw.cooling.d"] = ("Speeds the fans up before slowing the CPU down when it gets hot.", "وقتی داغ می‌شه اول فن‌ها رو تند می‌کنه، نه اینکه CPU رو کند کنه."),
        ["tw.overlay"] = ("Windows power mode: Best performance", "حالت انرژی ویندوز: بهترین کارایی"),
        ["tw.overlay.d"] = ("The slider in Settings → Power, moved all the way up.", "اسلایدر تنظیمات → انرژی، تا آخر بالا."),
        ["tw.overlay.na"] = ("(Windows offers it only with the Balanced plan.)", "(ویندوز این رو فقط با طرح Balanced ارائه می‌ده.)"),
        ["tw.foreground"] = ("Favour the program in front", "اولویت با برنامه‌ی جلوی صفحه"),
        ["tw.foreground.d"] = ("The window you are working in gets longer CPU turns than background work.", "پنجره‌ای که توش کار می‌کنی نسبت به کارهای پس‌زمینه سهم بیشتری از CPU می‌گیره."),

        ["svc.section"] = ("Background services", "سرویس‌های پس‌زمینه"),
        ["svc.SysMain"] = ("SysMain (Superfetch)", "SysMain (Superfetch)"),
        ["svc.SysMain.d"] = ("Pre-loads programs it thinks you will open. On a hard disk that is constant background reading; on an SSD it mostly does nothing.",
            "برنامه‌هایی که فکر می‌کنه باز می‌کنی رو از قبل بارگذاری می‌کنه. روی هارد دیسک یعنی خوندن دائمی در پس‌زمینه؛ روی SSD تقریباً هیچ کاری نمی‌کنه."),
        ["svc.WSearch"] = ("Windows Search indexing", "ایندکس جستجوی ویندوز"),
        ["svc.WSearch.d"] = ("Indexes every file that changes. On a machine that writes tens of thousands of build files, it keeps a core busy for nothing you search.",
            "هر فایلی که تغییر کنه رو ایندکس می‌کنه. روی سیستمی که ده‌ها هزار فایل بیلد می‌نویسه، یه هسته رو بی‌خود مشغول نگه می‌داره."),
        ["svc.ssd"] = ("Windows is on an SSD, so SysMain costs little either way. Search indexing is the one that matters on a build machine.",
            "ویندوز روی SSD هست، پس SysMain زیاد هزینه نداره. چیزی که روی سیستم برنامه‌نویسی مهمه ایندکس جستجوئه."),
        ["svc.hdd"] = ("Windows is on a hard disk. SysMain reads it in the background constantly; turning it off usually makes the machine feel quicker.",
            "ویندوز روی هارد دیسکه. SysMain مدام در پس‌زمینه ازش می‌خونه؛ خاموش کردنش معمولاً سیستم رو سریع‌تر نشون می‌ده."),
        ["svc.unknown"] = ("Could not tell whether Windows is on an SSD or a hard disk.", "معلوم نشد ویندوز روی SSD هست یا هارد دیسک."),
        ["svc.state"] = ("Starts: {0} · {1}", "شروع: {0} · {1}"),
        ["svc.start.Automatic"] = ("automatically", "خودکار"),
        ["svc.start.Manual"] = ("on demand", "در صورت نیاز"),
        ["svc.start.Disabled"] = ("never", "هیچ‌وقت"),
        ["svc.start.Missing"] = ("—", "—"),
        ["svc.running"] = ("running", "در حال اجرا"),
        ["svc.stopped"] = ("stopped", "متوقف"),
        ["svc.missing"] = ("Not on this PC", "روی این کامپیوتر نیست"),
        ["svc.turnedon"] = ("{0} turned on", "{0} روشن شد"),
        ["svc.turnedoff"] = ("{0} turned off", "{0} خاموش شد"),

        ["def.section"] = ("Antivirus (Microsoft Defender)", "آنتی‌ویروس (Microsoft Defender)"),
        ["def.unavailable"] = ("Defender is not answering — another antivirus may be in charge.", "Defender جواب نمی‌ده — شاید یه آنتی‌ویروس دیگه فعاله."),
        ["def.rt.on"] = ("Real-time protection on", "محافظت لحظه‌ای روشن"),
        ["def.rt.off"] = ("Real-time protection off", "محافظت لحظه‌ای خاموش"),
        ["def.mem"] = ("using {0} MB", "{0} مگابایت حافظه"),
        ["def.cap"] = ("scans capped at {0}% CPU", "اسکن محدود به {0}٪ CPU"),
        ["def.count"] = ("{0} folders excluded", "{0} پوشه مستثنا"),
        ["def.hidden"] = ("Windows shows the exclusion list only to administrators", "ویندوز لیست استثناها رو فقط به ادمین نشون می‌ده"),
        ["def.covered"] = ("Excluded ✓", "مستثنا ✓"),
        ["def.scanned"] = ("Scanned on every write", "با هر نوشتن اسکن می‌شه"),
        ["def.unknownstate"] = ("Unknown", "نامشخص"),
        ["def.exclude"] = ("Exclude {0} folders", "مستثنا کردن {0} پوشه"),
        ["def.nothing"] = ("Nothing to exclude", "چیزی برای مستثنا کردن نیست"),
        ["def.done"] = ("Defender no longer scans {0} cache folders", "Defender دیگه {0} پوشه‌ی کش رو اسکن نمی‌کنه"),
        ["def.realtime"] = ("Real-time protection", "محافظت لحظه‌ای"),
        ["def.realtime.d"] = ("Leave this on. Excluding the cache folders above gives back most of the speed without lowering protection.",
            "روشن بمونه. مستثنا کردن پوشه‌های کش بالا بیشتر سرعت رو برمی‌گردونه بدون اینکه امنیت کم بشه."),
        ["def.tamper"] = ("Tamper Protection is on, so only Windows Security can change this.", "Tamper Protection روشنه، پس فقط از Windows Security می‌شه تغییرش داد."),
        ["def.off.title"] = ("Turn off real-time protection?", "محافظت لحظه‌ای خاموش بشه؟"),
        ["def.off.q"] = ("Nothing will be scanned as it is opened or downloaded until it is turned back on. Windows also turns it back on by itself after a while.",
            "تا وقتی دوباره روشنش کنی هیچ فایلی موقع باز شدن یا دانلود اسکن نمی‌شه. ویندوز هم بعد از مدتی خودش دوباره روشنش می‌کنه."),
        ["def.off.go"] = ("Turn off", "خاموش کن"),
        ["def.temp"] = ("Temp files", "فایل‌های موقت"),
        ["def.npm"] = ("npm cache", "کش npm"),
        ["def.yarn"] = ("Yarn cache", "کش Yarn"),
        ["def.pnpm"] = ("pnpm store", "استور pnpm"),
        ["def.gradle"] = ("Gradle cache", "کش Gradle"),
        ["def.maven"] = ("Maven cache", "کش Maven"),
        ["def.cargo"] = ("Cargo cache", "کش Cargo"),
        ["def.nuget"] = ("NuGet packages", "پکیج‌های NuGet"),
        ["def.docker"] = ("Docker", "Docker"),
        ["def.vscode"] = ("VS Code extensions", "افزونه‌های VS Code"),
        ["def.programs"] = ("User-installed apps", "برنامه‌های نصب‌شده برای کاربر"),
        ["proc.title"] = ("Processes", "پردازش‌ها"),
        ["proc.sub"] = ("Everything running now, grouped by what it is. Dev servers (node, java, python…) are listed one by one with their command line, so you can tell which is which.",
            "هر چیزی که الان در حال اجراست، بر اساس نوعش. سرورهای توسعه (node، java، python و …) جدا جدا با خط فرمانشون نشون داده می‌شن تا معلوم باشه کدوم کدومه."),
        ["proc.memory"] = ("Memory", "حافظه"),
        ["proc.memof"] = ("{0} of {1}", "{0} از {1}"),
        ["proc.count"] = ("Processes", "تعداد پردازش"),
        ["proc.uptime"] = ("Up for", "روشن بودن"),
        ["proc.days"] = ("{0}d {1}h", "{0} روز {1} ساعت"),
        ["proc.hours"] = ("{0}h {1}m", "{0} ساعت {1} دقیقه"),
        ["proc.sort.cpu"] = ("By CPU", "بر اساس CPU"),
        ["proc.sort.mem"] = ("By memory", "بر اساس حافظه"),
        ["proc.sort.name"] = ("By name", "بر اساس نام"),
        ["proc.g.all"] = ("Everything", "همه"),
        ["proc.g.node"] = ("Node & tooling", "Node و ابزارها"),
        ["proc.g.build"] = ("Builds & runtimes", "بیلد و ران‌تایم‌ها"),
        ["proc.g.editor"] = ("Editors & IDEs", "ویرایشگرها و IDE"),
        ["proc.g.browser"] = ("Browsers", "مرورگرها"),
        ["proc.g.security"] = ("Antivirus", "آنتی‌ویروس"),
        ["proc.g.system"] = ("Windows", "ویندوز"),
        ["proc.g.other"] = ("Other", "سایر"),
        ["proc.p.idle"] = ("Idle", "بیکار"),
        ["proc.p.below"] = ("Below normal", "پایین‌تر از عادی"),
        ["proc.p.normal"] = ("Normal", "عادی"),
        ["proc.p.above"] = ("Above normal", "بالاتر از عادی"),
        ["proc.p.high"] = ("High", "بالا"),
        ["proc.end"] = ("End task", "بستن برنامه"),
        ["proc.end.one"] = ("End {0}? Anything unsaved in it is lost.", "{0} بسته بشه؟ هر چیزی که ذخیره نشده از دست می‌ره."),
        ["proc.end.many"] = ("End all {1} processes of {0}? Anything unsaved in them is lost.", "همه‌ی {1} پردازش {0} بسته بشن؟ هر چیزی که ذخیره نشده از دست می‌ره."),
        ["proc.ended"] = ("{0} ended", "{0} بسته شد"),
        ["proc.endfailed"] = ("{0} processes would not end — they may belong to another user or run as administrator.", "{0} پردازش بسته نشد — شاید مال کاربر دیگه‌ای باشن یا با دسترسی ادمین اجرا شده باشن."),
        ["proc.denied"] = ("Windows did not allow that — the process may run as administrator.", "ویندوز اجازه نداد — شاید پردازش با دسترسی ادمین اجرا شده."),
        ["proc.prioset"] = ("{0}: priority {1}", "{0}: اولویت {1}"),
        ["proc.lowered"] = ("{0} now yields to what you are working in", "{0} حالا جا رو برای کاری که انجام می‌دی باز می‌کنه"),
        ["proc.f.mem"] = ("Memory is {0}% full — the machine will start swapping to disk. {1} hold the most: {2}.", "حافظه {0}٪ پره — سیستم شروع به استفاده از دیسک می‌کنه. بیشترین سهم مال {1}ه: {2}."),
        ["proc.f.memwarn"] = ("Memory is {0}% used. {1} hold the most: {2}.", "{0}٪ حافظه استفاده شده. بیشترین سهم مال {1}ه: {2}."),
        ["proc.f.uptime"] = ("Windows has been up {0} days with memory filling up — a restart clears what programs leaked.", "ویندوز {0} روزه روشنه و حافظه داره پر می‌شه — یه ری‌استارت چیزهایی که برنامه‌ها نشت دادن رو پاک می‌کنه."),
        ["proc.f.cpu"] = ("{0} is using {1}% of the CPU. Lowering its priority keeps the rest of the machine responsive.", "{0} داره {1}٪ از CPU رو مصرف می‌کنه. پایین آوردن اولویتش بقیه‌ی سیستم رو روان نگه می‌داره."),
        ["proc.f.lower"] = ("Lower its priority", "اولویتش رو کم کن"),
        ["proc.f.disk"] = ("{0} has only {1} free.", "روی {0} فقط {1} جا مونده."),
        ["prog.title"] = ("Installed programs", "برنامه‌های نصب‌شده"),
        ["prog.sub"] = ("Everything in Add/Remove and the Store, biggest first. Uninstall runs the program's own uninstaller; then Rocket finds the folders it left behind.",
            "همه‌ی برنامه‌های Add/Remove و Store، بزرگ‌ترها اول. «حذف نصب» حذف‌کننده‌ی خود برنامه رو اجرا می‌کنه؛ بعد Rocket پوشه‌هایی که جا گذاشته رو پیدا می‌کنه."),
        ["prog.summary"] = ("{0} programs · {1} from the Store", "{0} برنامه · {1} از Store"),
        ["prog.quiet"] = ("Quiet where possible", "بی‌صدا در صورت امکان"),
        ["prog.sort.size"] = ("By size", "بر اساس حجم"),
        ["prog.sort.name"] = ("By name", "بر اساس نام"),
        ["prog.sort.date"] = ("By date", "بر اساس تاریخ"),
        ["prog.sort.publisher"] = ("By publisher", "بر اساس ناشر"),
        ["prog.f.all"] = ("All", "همه"),
        ["prog.f.desktop"] = ("Desktop", "دسکتاپ"),
        ["prog.f.store"] = ("Store", "Store"),
        ["prog.f.large"] = ("Large (500 MB+)", "حجیم (+۵۰۰ مگ)"),
        ["prog.f.recent"] = ("Last 30 days", "۳۰ روز اخیر"),
        ["prog.f.broken"] = ("No uninstaller", "بدون حذف‌کننده"),
        ["prog.dependency"] = ("Needed by others", "پیش‌نیاز بقیه"),
        ["prog.broken"] = ("No uninstaller", "بدون حذف‌کننده"),
        ["prog.uninstall"] = ("Uninstall", "حذف نصب"),
        ["prog.force"] = ("Remove from list", "حذف از لیست"),
        ["prog.removing"] = ("Removing…", "در حال حذف…"),
        ["prog.removed"] = ("Removed", "حذف شد"),
        ["prog.uninstall.q"] = ("Uninstall {0}? Its own uninstaller runs; Rocket then looks for what it left behind.", "{0} حذف نصب بشه؟ حذف‌کننده‌ی خودش اجرا می‌شه؛ بعد Rocket دنبال چیزهایی که جا گذاشته می‌گرده."),
        ["prog.dep.warn"] = ("This looks like a runtime or driver other programs need. Remove it only if you know nothing uses it.", "این شبیه یه ران‌تایم یا درایوره که برنامه‌های دیگه لازمش دارن. فقط اگه مطمئنی چیزی ازش استفاده نمی‌کنه حذفش کن."),
        ["prog.force.q"] = ("{0} has no working uninstaller. Take it out of the installed list? Its files are not touched here — leftovers are offered next.", "{0} حذف‌کننده‌ی سالمی نداره. از لیست برنامه‌ها حذف بشه؟ فایل‌هاش اینجا دست نمی‌خورن — باقی‌مانده‌ها بعدش پیشنهاد می‌شن."),
        ["prog.nouninstaller"] = ("This program did not register an uninstaller.", "این برنامه حذف‌کننده‌ای ثبت نکرده."),
        ["prog.missing"] = ("The uninstaller is missing: {0}", "حذف‌کننده پیدا نشد: {0}"),
        ["prog.stillrunning"] = ("The uninstaller is still running — finish it, then scan again.", "حذف‌کننده هنوز در حال اجراست — تمومش کن و دوباره اسکن کن."),
        ["prog.notremoved"] = ("The program is still installed — the uninstaller may have been cancelled.", "برنامه هنوز نصبه — شاید حذف‌کننده لغو شده."),
        ["prog.log"] = ("Uninstalled {0}", "{0} حذف نصب شد"),
        ["prog.done"] = ("{0} is gone and left nothing behind", "{0} حذف شد و چیزی جا نذاشت"),
        ["prog.done.lo"] = ("{0} is gone — it left {1} behind", "{0} حذف شد — {1} جا گذاشته"),
        ["prog.lo.install"] = ("Install folder the uninstaller left behind", "پوشه‌ی نصب که حذف‌کننده جا گذاشته"),
        ["prog.lo.data"] = ("Settings and data folder", "پوشه‌ی تنظیمات و داده‌ها"),
        ["pc.title"] = ("This PC", "این کامپیوتر"),
        ["pc.sub"] = ("Everything in the box, and what the board could take instead: a stronger processor, more memory, faster storage.",
            "هر چیزی که توی کیس هست، و چیزی که مادربرد می‌تونه به جاش بگیره: پردازنده‌ی قوی‌تر، رم بیشتر، حافظه‌ی سریع‌تر."),
        ["pc.reading"] = ("Reading the hardware…", "در حال خوندن مشخصات سخت‌افزار…"),
        ["pc.failed"] = ("Windows did not answer the hardware query.", "ویندوز به درخواست مشخصات سخت‌افزار جواب نداد."),
        ["pc.copy"] = ("Copy specs", "کپی مشخصات"),
        ["pc.copied"] = ("Specs copied", "مشخصات کپی شد"),
        ["pc.banner"] = ("{0} upgrades this box can take", "{0} ارتقا که این سیستم می‌تونه بگیره"),
        ["pc.banner.none"] = ("Nothing obvious to upgrade", "ارتقای مشخصی لازم نیست"),
        ["pc.cpu"] = ("Processor", "پردازنده"),
        ["pc.model"] = ("Model", "مدل"),
        ["pc.cores"] = ("Cores", "هسته‌ها"),
        ["pc.coresval"] = ("{0} cores / {1} threads", "{0} هسته / {1} رشته"),
        ["pc.clock"] = ("Rated clock", "سرعت اسمی"),
        ["pc.cache"] = ("Cache", "کش"),
        ["pc.socket"] = ("Socket", "سوکت"),
        ["pc.memory"] = ("Memory", "حافظه (رم)"),
        ["pc.total"] = ("Installed", "نصب‌شده"),
        ["pc.slots"] = ("Slots", "اسلات‌ها"),
        ["pc.slotsval"] = ("{0} of {1} in use", "{0} از {1} پر"),
        ["pc.max"] = ("Board maximum", "حداکثر مادربرد"),
        ["pc.gpu"] = ("Graphics", "گرافیک"),
        ["pc.storage"] = ("Storage", "حافظه‌ی ذخیره‌سازی"),
        ["pc.freeof"] = ("{0} free", "{0} آزاد"),
        ["pc.board"] = ("Board & firmware", "مادربرد و BIOS"),
        ["pc.computer"] = ("Computer", "کامپیوتر"),
        ["pc.boardname"] = ("Motherboard", "مادربرد"),
        ["pc.windows"] = ("Windows & network", "ویندوز و شبکه"),
        ["pc.edition"] = ("Edition", "نسخه"),
        ["pc.build"] = ("Build", "بیلد"),
        ["pc.installed"] = ("Installed", "تاریخ نصب"),
        ["pc.up"] = ("connected", "وصل"),
        ["pc.down"] = ("not connected", "قطع"),

        ["adv.ram.soldered"] = ("Memory is soldered on this laptop", "رم روی این لپ‌تاپ لحیم شده"),
        ["adv.ram.soldered.w"] = ("It cannot be added to or replaced.", "نمی‌شه بهش اضافه کرد یا عوضش کرد."),
        ["adv.ram.maxed"] = ("Memory is maxed at {0} GB", "رم روی حداکثر {0} گیگه"),
        ["adv.ram.maxed.w"] = ("The board takes no more.", "مادربرد بیشتر از این نمی‌گیره."),
        ["adv.ram.add"] = ("Add {0} GB of RAM: {1} of {2} slots are empty", "{0} گیگ رم اضافه کن: {1} از {2} اسلات خالیه"),
        ["adv.ram.add.w"] = ("You have {0} GB. On a machine that runs editors, browsers and builds together, memory runs out first.", "الان {0} گیگ داری. روی سیستمی که ادیتور، مرورگر و بیلد با هم اجرا می‌کنه، اول رم تموم می‌شه."),
        ["adv.ram.add.s"] = ("{0} × {1} GB {2}-{3} {4}, same speed as the sticks already in.", "{0} عدد {1} گیگ {2}-{3} {4}، هم‌سرعت با رم‌های فعلی."),
        ["adv.ram.replace"] = ("Every slot is full, but {0} GB more is possible", "همه‌ی اسلات‌ها پرن، ولی {0} گیگ بیشتر ممکنه"),
        ["adv.ram.replace.w"] = ("Replace the smaller sticks with {0} GB ones.", "رم‌های کوچیک‌تر رو با {0} گیگی عوض کن."),
        ["adv.ram.mixed"] = ("Mixed memory speeds: everything runs at {0} MHz", "سرعت رم‌ها یکی نیست: همه با {0} مگاهرتز کار می‌کنن"),
        ["adv.ram.mixed.w"] = ("Sticks run at the speed of the slowest one.", "همه‌ی رم‌ها با سرعت کندترینشون کار می‌کنن."),
        ["adv.ram.tight"] = ("{0} GB is tight for today's software", "{0} گیگ برای نرم‌افزارهای امروزی کمه"),
        ["adv.ram.tight.w"] = ("16 GB is the floor; 32 GB if you run emulators, VMs or Docker.", "۱۶ گیگ حداقله؛ اگه امولاتور، ماشین مجازی یا Docker اجرا می‌کنی ۳۲ گیگ."),
        ["adv.cpu.mobile"] = ("The processor cannot be swapped", "پردازنده قابل تعویض نیست"),
        ["adv.cpu.mobile.w"] = ("Laptop processors are soldered to the board.", "پردازنده‌ی لپ‌تاپ روی برد لحیم شده."),
        ["adv.cpu.top"] = ("{0} is the top chip for socket {1}", "{0} قوی‌ترین پردازنده‌ی سوکت {1} هست"),
        ["adv.cpu.top.w"] = ("A faster processor would need a new board.", "پردازنده‌ی سریع‌تر مادربرد جدید می‌خواد."),
        ["adv.cpu.fits"] = ("A {0} fits this board", "یه {0} روی این مادربرد جا می‌شه"),
        ["adv.cpu.fits.w"] = ("Socket {0}, a platform from {1} years ago — the best chip it takes: {2}. Usually cheap second-hand.", "سوکت {0}، پلتفرمی از {1} سال پیش — بهترین پردازنده‌ای که می‌گیره: {2}. معمولاً دست‌دوم ارزونه."),
        ["adv.cpu.fits.s"] = ("Update the BIOS first (a version from {0} or later).", "اول BIOS رو آپدیت کن (نسخه‌ی {0} یا جدیدتر)."),
        ["adv.cpu.unknown"] = ("Could not place this processor on a socket", "سوکت این پردازنده شناسایی نشد"),
        ["adv.cpu.unknown.w"] = ("Check the board's support list for faster chips.", "لیست پردازنده‌های پشتیبانی‌شده‌ی مادربرد رو ببین."),
        ["adv.gpu.igpu.mobile"] = ("Integrated graphics only", "فقط گرافیک آنبورد"),
        ["adv.gpu.igpu.mobile.w"] = ("An external GPU over Thunderbolt is the only way up.", "تنها راه، کارت گرافیک اکسترنال از طریق Thunderbolt هست."),
        ["adv.gpu.none"] = ("No dedicated graphics card", "کارت گرافیک مجزا نداره"),
        ["adv.gpu.none.w"] = ("Emulators, design tools and local AI models all lean on the GPU.", "امولاتورها، ابزارهای طراحی و مدل‌های هوش مصنوعی محلی همه به GPU تکیه دارن."),
        ["adv.gpu.none.s"] = ("An RX 7600 or RTX 4060 class card, with a 450 W+ power supply.", "یه کارت در حد RX 7600 یا RTX 4060، با پاور ۴۵۰ وات به بالا."),
        ["adv.gpu.weak"] = ("{0} is an entry-level card", "{0} یه کارت سطح پایینه"),
        ["adv.gpu.weak.w"] = ("Fine for the desktop; slow for local AI or emulators.", "برای کار روزمره خوبه؛ برای هوش مصنوعی محلی یا امولاتور کنده."),
        ["adv.gpu.good"] = ("{0} is a capable card", "{0} کارت توانمندیه"),
        ["adv.disk.hdd"] = ("Windows is on a hard disk — an SSD is the single biggest upgrade", "ویندوز روی هارد دیسکه — SSD بزرگ‌ترین ارتقای ممکنه"),
        ["adv.disk.hdd.w"] = ("Everything opens several times faster.", "همه‌چیز چند برابر سریع‌تر باز می‌شه."),
        ["adv.disk.nvme.s"] = ("The board takes NVMe — that is the one to buy.", "مادربرد NVMe می‌گیره — همون رو بخر."),
        ["adv.disk.sata.s"] = ("A SATA SSD is what this board takes.", "این مادربرد SSD ساتا می‌گیره."),
        ["adv.disk.satanvme"] = ("Windows is on a SATA SSD; the board can take NVMe", "ویندوز روی SSD ساتا هست؛ مادربرد NVMe هم می‌گیره"),
        ["adv.disk.satanvme.w"] = ("NVMe is several times faster for builds and installs.", "NVMe برای بیلد و نصب چند برابر سریع‌تره."),
        ["adv.disk.sataceil"] = ("Windows is on a SATA SSD, the ceiling for this board", "ویندوز روی SSD ساتا هست، که سقف این مادربرده"),
        ["adv.disk.sataceil.w"] = ("A bigger SATA SSD is the only way up.", "تنها راه، SSD ساتای بزرگ‌تره."),
        ["adv.disk.fast"] = ("Windows is on a fast SSD", "ویندوز روی SSD سریعه"),
        ["adv.disk.full"] = ("{0} is nearly full", "{0} تقریباً پره"),
        ["adv.disk.full.w"] = ("Below 10% free, Windows and SSDs both slow down. Quick clean and Projects free the most.", "زیر ۱۰٪ فضای خالی، هم ویندوز و هم SSD کند می‌شن. پاک‌سازی سریع و پروژه‌ها بیشترین فضا رو آزاد می‌کنن."),
        ["adv.os.unsupported"] = ("Windows 11 on a processor Microsoft does not list for it", "ویندوز ۱۱ روی پردازنده‌ای که مایکروسافت پشتیبانی نمی‌کنه"),
        ["adv.os.unsupported.w"] = ("It works, but feature updates may stop arriving.", "کار می‌کنه، ولی شاید آپدیت‌های اصلی دیگه نیان."),
        ["adv.os.win10"] = ("Windows 10 stopped getting security updates in October 2025", "ویندوز ۱۰ از اکتبر ۲۰۲۵ آپدیت امنیتی نمی‌گیره"),
        ["adv.os.win10.w"] = ("Plan the move to Windows 11.", "برای مهاجرت به ویندوز ۱۱ برنامه‌ریزی کن."),
        ["ov.title"] = ("Make this PC fast again", "این کامپیوتر رو دوباره سریع کن"),
        ["ov.sub"] = ("Free the space your tools and AI models left behind, let the processor run at full speed, and see what is slowing the machine down — all in one place.",
            "فضایی که ابزارها و مدل‌های هوش مصنوعی گرفتن رو آزاد کن، بذار پردازنده با تمام سرعت کار کنه، و ببین چی سیستم رو کند کرده — همه در یک جا."),
        ["ov.space"] = ("Free up space", "آزادسازی فضا"),
        ["ov.space.tag"] = ("Delete only what comes back", "فقط چیزی که دوباره ساخته می‌شه پاک می‌شه"),
        ["ov.space.sub"] = ("{0} in caches and leftovers · {1} in projects", "{0} کش و باقی‌مانده · {1} در پروژه‌ها"),
        ["ov.space.models"] = ("{0} in AI models", "{0} مدل هوش مصنوعی"),
        ["ov.space.free"] = ("free across your drives", "فضای آزاد روی درایوها"),
        ["ov.speed"] = ("Speed up", "افزایش سرعت"),
        ["ov.speed.tag"] = ("Run at the speed you paid for", "با سرعتی که براش پول دادی کار کن"),
        ["ov.watch"] = ("Keep watch", "زیر نظر داشتن"),
        ["ov.watch.tag"] = ("Know what is slowing it down", "بدون چی کندش کرده"),
        ["ov.mem"] = ("{0}% memory", "{0}٪ حافظه"),
        ["ov.watch.sub"] = ("{0} of {1} · CPU {2}%", "{0} از {1} · CPU {2}٪"),
        ["ov.drives"] = ("Drives", "درایوها"),
        ["ov.alert.disk"] = ("{0} has only {1} left — Quick clean frees the most in one go.", "روی {0} فقط {1} جا مونده — پاک‌سازی سریع بیشترین فضا رو یک‌جا آزاد می‌کنه."),
        ["ov.alert.cpu"] = ("The CPU is busy but held to {0}% of its clock.", "CPU مشغوله ولی روی {0}٪ سرعتش نگه داشته شده."),
        ["ov.alert.mem"] = ("Memory is {0}% full — see what holds it.", "حافظه {0}٪ پره — ببین چی گرفتتش."),
        ["ov.safety"] = ("Rocket never deletes your files, only what tools rebuild by themselves — and asks before anything goes. Every system change can be put back.",
            "Rocket هیچ‌وقت فایل‌های شما رو پاک نمی‌کنه، فقط چیزهایی که ابزارها خودشون دوباره می‌سازن — و قبل از هر حذفی می‌پرسه. هر تغییر سیستمی برگشت‌پذیره."),
        ["move.tip"] = ("Move to another drive", "انتقال به درایو دیگه"),
        ["move.project"] = ("Move this project to another drive", "انتقال این پروژه به درایو دیگه"),
        ["move.pick"] = ("Where should it go?", "به کجا منتقل بشه؟"),
        ["move.weighing"] = ("Measuring what has to travel…", "در حال اندازه‌گیری چیزی که باید منتقل بشه…"),
        ["move.title"] = ("Move to another drive?", "به درایو دیگه منتقل بشه؟"),
        ["move.body"] = ("{0}\n→ {1}\n\n{2} in {3} files. Copied first and checked file by file; only then is the original removed.",
            "{0}\n← {1}\n\n{2} در {3} فایل. اول کپی و فایل‌به‌فایل بررسی می‌شه؛ فقط بعدش اصلی پاک می‌شه."),
        ["move.rebuilt"] = ("{0} of node_modules, builds and caches stays behind and is deleted — npm install or the next build makes it again.",
            "{0} از node_modules، بیلدها و کش‌ها منتقل نمی‌شه و پاک می‌شه — npm install یا بیلد بعدی دوباره می‌سازدش."),
        ["move.go"] = ("Move", "منتقل کن"),
        ["move.running"] = ("Moving", "در حال انتقال"),
        ["move.pill"] = ("{0} moved", "{0} منتقل شد"),
        ["move.done"] = ("Moved", "منتقل شد"),
        ["move.failed"] = ("Not moved", "منتقل نشد"),
        ["move.now"] = ("It now lives at {0}", "حالا اینجاست: {0}"),
        ["move.cancelled"] = ("Stopped. The original is untouched; the partial copy is still at the destination.", "متوقف شد. اصلی دست نخورده؛ کپی ناقص هنوز در مقصد هست."),
        ["move.log"] = ("Moved {0} to {1}", "{0} به {1} منتقل شد"),
        ["move.p.source"] = ("That folder is gone.", "اون پوشه دیگه وجود نداره."),
        ["move.p.protected"] = ("That is a Windows or program folder; Rocket does not move those.", "این پوشه‌ی ویندوز یا برنامه‌هاست؛ Rocket اینا رو جابه‌جا نمی‌کنه."),
        ["move.p.dest"] = ("The destination folder does not exist.", "پوشه‌ی مقصد وجود نداره."),
        ["move.p.inside"] = ("A folder cannot be moved into itself.", "یه پوشه رو نمی‌شه به داخل خودش منتقل کرد."),
        ["move.p.exists"] = ("{0} already exists — nothing is overwritten.", "{0} از قبل وجود داره — چیزی بازنویسی نمی‌شه."),
        ["move.p.space"] = ("Only {0} free at the destination.", "در مقصد فقط {0} جا هست."),
        ["move.e.copy"] = ("The copy failed (robocopy {0}); the original is untouched.", "کپی ناموفق بود (robocopy {0})؛ اصلی دست نخورده."),
        ["move.e.verify"] = ("The copy does not match ({0} of {1} files); the original is untouched.", "کپی با اصلی یکی نیست ({0} از {1} فایل)؛ اصلی دست نخورده."),
        ["move.e.left"] = ("Copied, but {0} files of the original were in use and stayed.", "کپی شد، ولی {0} فایل از اصلی در حال استفاده بودن و موندن."),
        ["progress.title"] = ("Cleaning", "در حال پاک‌سازی"),
        ["progress.freed"] = ("freed", "آزاد شد"),
        ["progress.done"] = ("Done", "تمام شد"),
        ["progress.skipped"] = ("{0} files were in use and were left alone.", "{0} فایل در حال استفاده بودن و دست نخوردن."),
        ["progress.drives"] = ("Now free: {0}", "فضای آزاد الان: {0}"),
        ["progress.stop"] = ("Stop", "توقف"),
    };
}
