/**
 * Real filesystem scanner for the Electron main process.
 *
 * Produces objects that match the renderer's `Project` type in src/types/project.ts
 * exactly, so the UI needs no translation layer.
 */
const fsp = require('node:fs/promises')
const fs = require('node:fs')
const path = require('node:path')

/** Directories we never walk into while looking for projects. */
const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  '.svn',
  '.hg',
  '.idea',
  '.vscode',
  '.gradle',
  '.cxx',
  '.next',
  '.turbo',
  '.cache',
  'dist',
  'build',
  'out',
  'target',
  'bin',
  'obj',
  'Pods',
  'vendor',
  'venv',
  '.venv',
  '__pycache__',
  'AppData',
  'Windows',
  'Program Files',
  'Program Files (x86)',
  'ProgramData',
  '$RECYCLE.BIN',
  'System Volume Information',
  'Recovery',
  'PerfLogs',
  'Windows.old',
  'MSOCache',
  'Intel',
  'NVIDIA',
  'AMD',
  'OneDriveTemp',
  'WindowsApps',
  'Config.Msi',
])

/**
 * Only folders whose final segment is in this list may ever be deleted.
 * This is the last line of defence against a bad path from the renderer.
 */
const REMOVABLE_FOLDERS = new Set([
  'node_modules',
  '.next',
  '.nuxt',
  '.svelte-kit',
  '.turbo',
  '.cache',
  '.parcel-cache',
  '.angular',
  '.astro',
  '.vite',
  '.output',
  '.expo',
  '.docusaurus',
  '.vercel',
  '.netlify',
  '.dart_tool',
  'dist',
  'build',
  'out',
  'coverage',
  'storybook-static',
  '.gradle',
  '.cxx',
  '.kotlin',
  'captures',
  'pods',
])

const NPM = 'Restored by `npm install`'
const GRADLE = 'Rebuilt on next Gradle sync'
const NDK = 'Triggers a full NDK rebuild (slow)'

const NODE_CANDIDATES = [
  { folder: 'node_modules', segments: ['node_modules'], restoredBy: NPM },
  { folder: '.next', segments: ['.next'], restoredBy: 'Rebuilt on next `next build`' },
  { folder: '.nuxt', segments: ['.nuxt'], restoredBy: 'Rebuilt on next Nuxt build' },
  { folder: '.output', segments: ['.output'], restoredBy: 'Rebuilt on next Nitro build' },
  { folder: '.svelte-kit', segments: ['.svelte-kit'], restoredBy: 'Rebuilt on next SvelteKit build' },
  { folder: '.angular', segments: ['.angular'], restoredBy: 'Rebuilt on next Angular build' },
  { folder: '.astro', segments: ['.astro'], restoredBy: 'Rebuilt on next Astro build' },
  { folder: 'dist', segments: ['dist'], restoredBy: 'Rebuilt on next build' },
  { folder: 'build', segments: ['build'], restoredBy: 'Rebuilt on next build' },
  { folder: 'out', segments: ['out'], restoredBy: 'Rebuilt on next build' },
  { folder: '.turbo', segments: ['.turbo'], restoredBy: 'Rebuilt on next Turbo run' },
  { folder: '.cache', segments: ['.cache'], restoredBy: 'Rebuilt automatically on dev start' },
  { folder: '.parcel-cache', segments: ['.parcel-cache'], restoredBy: 'Rebuilt on next Parcel run' },
  { folder: '.vite', segments: ['.vite'], restoredBy: 'Rebuilt on next Vite start' },
  { folder: '.docusaurus', segments: ['.docusaurus'], restoredBy: 'Rebuilt on next Docusaurus build' },
  { folder: '.vercel', segments: ['.vercel'], restoredBy: 'Rebuilt on next `vercel build`' },
  { folder: '.netlify', segments: ['.netlify'], restoredBy: 'Rebuilt on next Netlify build' },
  { folder: '.expo', segments: ['.expo'], restoredBy: 'Rebuilt on next Expo start' },
  { folder: 'coverage', segments: ['coverage'], restoredBy: 'Regenerated by your test run' },
  { folder: 'storybook-static', segments: ['storybook-static'], restoredBy: 'Rebuilt by `build-storybook`' },
  { folder: 'android/build', segments: ['android', 'build'], restoredBy: GRADLE },
  { folder: 'android/app/build', segments: ['android', 'app', 'build'], restoredBy: GRADLE },
  { folder: 'android/.gradle', segments: ['android', '.gradle'], restoredBy: GRADLE },
  { folder: 'android/.cxx', segments: ['android', '.cxx'], restoredBy: NDK, safety: 'caution' },
  { folder: 'ios/Pods', segments: ['ios', 'Pods'], restoredBy: 'Restored by `pod install`' },
]

const ANDROID_CANDIDATES = [
  { folder: 'build', segments: ['build'], restoredBy: GRADLE },
  { folder: '.gradle', segments: ['.gradle'], restoredBy: GRADLE },
  { folder: '.kotlin', segments: ['.kotlin'], restoredBy: GRADLE },
  { folder: '.cxx', segments: ['.cxx'], restoredBy: NDK, safety: 'caution' },
  {
    folder: 'captures',
    segments: ['captures'],
    restoredBy: 'Profiler captures are not regenerated',
    safety: 'caution',
  },
]

async function exists(target) {
  try {
    await fsp.access(target)
    return true
  } catch {
    return false
  }
}

async function isDirectory(target) {
  try {
    return (await fsp.stat(target)).isDirectory()
  } catch {
    return false
  }
}

async function readJson(file) {
  try {
    return JSON.parse(await fsp.readFile(file, 'utf8'))
  } catch {
    return null
  }
}

const GRADLE_MARKERS = ['build.gradle', 'build.gradle.kts', 'settings.gradle', 'settings.gradle.kts', 'gradlew']

/**
 * A user's profile folder or a drive root is never a project, whatever stray
 * package.json it holds: treating it as one would offer to move or delete
 * the whole account.
 */
function isRootLike(dir) {
  // "D:" alone would resolve to the current folder on D:, so it is answered first.
  if (/^[A-Za-z]:[\\/]*$/.test(String(dir))) return true
  const normalized = path.resolve(dir).replace(/[\\/]+$/, '')
  if (/^[A-Za-z]:$/.test(normalized)) return true
  if (/^[A-Za-z]:\\Users\\[^\\]+$/i.test(normalized)) return true
  const home = (process.env.USERPROFILE || '').replace(/[\\/]+$/, '').toLowerCase()
  return Boolean(home) && normalized.toLowerCase() === home
}

/** Classifies a directory from the file names it already contains — no I/O. */
function kindFromNames(names) {
  if (names.has('package.json')) return 'node'
  for (const marker of GRADLE_MARKERS) {
    if (names.has(marker)) return 'android'
  }
  return null
}

async function detectKind(dir) {
  let entries
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return null
  }
  const names = new Set()
  entries.forEach((entry) => {
    if (entry.isFile()) names.add(entry.name)
  })
  return kindFromNames(names)
}

function majorVersion(range) {
  if (typeof range !== 'string') return ''
  const match = range.match(/(\d+)(?:\.(\d+))?/)
  return match ? match[1] : ''
}

async function nodeFramework(dir) {
  const pkg = await readJson(path.join(dir, 'package.json'))
  if (!pkg) return 'Node project'
  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) }
  const has = (name) => Boolean(deps[name])
  const version = (name) => majorVersion(deps[name])

  if (has('next')) return `Next.js ${version('next')}`.trim()
  if (has('react-native')) return `React Native ${deps['react-native'].replace(/[^0-9.]/g, '')}`.trim()
  if (has('@remix-run/react')) return `Remix ${version('@remix-run/react')}`.trim()
  if (has('astro')) return `Astro ${version('astro')}`.trim()
  if (has('nuxt')) return `Nuxt ${version('nuxt')}`.trim()
  if (has('@angular/core')) return `Angular ${version('@angular/core')}`.trim()
  if (has('electron')) return `Electron ${version('electron')}`.trim()
  if (has('react-scripts')) return 'Create React App'
  if (has('vite') && has('react')) return 'Vite + React'
  if (has('vite') && has('svelte')) return 'Vite + Svelte'
  if (has('vite') && has('vue')) return 'Vite + Vue'
  if (has('vite')) return 'Vite project'
  if (has('react')) return `React ${version('react')}`.trim()
  if (has('express') || has('fastify')) return 'Node service'
  return 'Node project'
}

async function androidFramework(dir) {
  let gradleVersion = ''
  try {
    const properties = await fsp.readFile(path.join(dir, 'gradle', 'wrapper', 'gradle-wrapper.properties'), 'utf8')
    const match = properties.match(/gradle-([\d.]+)-/)
    if (match) gradleVersion = match[1]
  } catch {
    /* no wrapper, fall back to a plain label */
  }
  const usesKotlinDsl =
    (await exists(path.join(dir, 'build.gradle.kts'))) || (await exists(path.join(dir, 'settings.gradle.kts')))
  const label = gradleVersion ? `Gradle ${gradleVersion}` : 'Gradle'
  return `${label} · ${usesKotlinDsl ? 'Kotlin DSL' : 'Groovy'}`
}

/** How wide the walk fans out. The job manager lowers this in gentle mode. */
const DEFAULT_TUNING = { fileBatch: 128, dirBatch: 12, deleteBatch: 64 }

/** Cancellation and pause are both polled here, at every batch boundary. */
async function checkpoint(state) {
  if (state.wait) await state.wait()
  return state.cancelled
}

/** Recursively measure a tree, optionally skipping a set of absolute paths. */
async function measureTree(dir, state, exclude, tuning = DEFAULT_TUNING) {
  if (await checkpoint(state)) return { bytes: 0, files: 0 }

  let entries
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return { bytes: 0, files: 0 }
  }

  let bytes = 0
  let files = 0
  const childDirs = []
  const childFiles = []

  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (exclude && exclude.has(full.toLowerCase())) continue
      childDirs.push(full)
    } else if (entry.isFile()) {
      childFiles.push(full)
    }
  }

  // Windows stat calls go through Defender's filter driver, so the walk is
  // latency-bound rather than CPU-bound — a deep queue hides most of that.
  for (let index = 0; index < childFiles.length; index += tuning.fileBatch) {
    if (await checkpoint(state)) break
    const chunk = childFiles.slice(index, index + tuning.fileBatch)
    const stats = await Promise.all(
      chunk.map((file) =>
        fsp.stat(file).then(
          (stat) => stat.size,
          () => 0,
        ),
      ),
    )
    stats.forEach((size) => {
      bytes += size
      files += 1
    })
  }

  for (let index = 0; index < childDirs.length; index += tuning.dirBatch) {
    if (await checkpoint(state)) break
    const chunk = childDirs.slice(index, index + tuning.dirBatch)
    const results = await Promise.all(chunk.map((child) => measureTree(child, state, exclude, tuning)))
    results.forEach((result) => {
      bytes += result.bytes
      files += result.files
    })
  }

  return { bytes, files }
}

async function androidModuleCandidates(dir) {
  const candidates = []
  let entries
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return candidates
  }
  for (const entry of entries) {
    if (!entry.isDirectory() || entry.isSymbolicLink()) continue
    if (entry.name.startsWith('.') || entry.name === 'gradle' || entry.name === 'build') continue
    const isModule =
      (await exists(path.join(dir, entry.name, 'build.gradle'))) ||
      (await exists(path.join(dir, entry.name, 'build.gradle.kts')))
    if (!isModule) continue
    candidates.push({
      folder: `${entry.name}/build`,
      segments: [entry.name, 'build'],
      restoredBy: GRADLE,
    })
    candidates.push({
      folder: `${entry.name}/.cxx`,
      segments: [entry.name, '.cxx'],
      restoredBy: NDK,
      safety: 'caution',
    })
  }
  return candidates
}

/**
 * Reads one directory and decides, from the names it already got back, whether
 * this is a project or somewhere to keep looking.
 *
 * The old version asked the filesystem seven times per directory — six
 * `exists` probes for the marker files, then a `readdir` to descend. One
 * `readdir` answers both questions, which is most of why discovery went from
 * three minutes to seconds.
 */
async function inspectDirectory(dir, level, maxDepth) {
  let entries
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return null
  }

  const names = new Set()
  const children = []

  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue
    if (entry.isDirectory()) {
      if (level >= maxDepth) continue
      if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('$')) continue
      children.push(path.join(dir, entry.name))
    } else if (entry.isFile()) {
      names.add(entry.name)
    }
  }

  return { dir, kind: kindFromNames(names), children }
}

/**
 * Breadth-first walk of `root` that stops descending once a project is found.
 *
 * A level is read in parallel rather than one directory at a time: the walk is
 * latency-bound, so the width is what makes it quick.
 *
 * `onFound` fires for every project directory as it is discovered, so a scan of
 * a big drive can report progress while the walk is still running.
 */
async function findProjects(root, state, maxDepth = 4, onFound, width = 32) {
  const found = []
  let frontier = [{ dir: root, level: 0 }]

  while (frontier.length > 0) {
    if (await checkpoint(state)) break
    const next = []

    for (let index = 0; index < frontier.length; index += width) {
      if (await checkpoint(state)) break
      const chunk = frontier.slice(index, index + width)
      const results = await Promise.all(
        chunk.map((entry) => inspectDirectory(entry.dir, entry.level, maxDepth)),
      )

      results.forEach((result, offset) => {
        if (!result) return
        if (result.kind && !isRootLike(result.dir)) {
          found.push(result.dir)
          if (onFound) onFound(result.dir, found.length)
          return
        }
        const level = chunk[offset].level + 1
        result.children.forEach((child) => next.push({ dir: child, level }))
      })
    }

    frontier = next
  }

  return found
}

/** True when `child` sits inside one of the already-claimed absolute paths. */
function isNestedIn(child, claimed) {
  const lower = child.toLowerCase()
  for (const parent of claimed) {
    if (lower === parent || lower.startsWith(`${parent}${path.sep}`)) return true
  }
  return false
}

async function measureProject(dir, id, state, tuning = DEFAULT_TUNING) {
  if (isRootLike(dir)) return null
  const kind = await detectKind(dir)
  if (!kind) return null

  const candidates =
    kind === 'node' ? NODE_CANDIDATES : [...ANDROID_CANDIDATES, ...(await androidModuleCandidates(dir))]

  const targets = []
  const exclude = new Set()

  for (const candidate of candidates) {
    if (await checkpoint(state)) return null
    const absolute = path.join(dir, ...candidate.segments)
    if (!(await isDirectory(absolute))) continue
    // Skip anything already inside a claimed target, or it would be measured
    // and deleted twice.
    if (isNestedIn(absolute, exclude)) continue

    const { bytes, files } = await measureTree(absolute, state, null, tuning)
    if (files === 0 && bytes === 0) continue

    exclude.add(absolute.toLowerCase())
    targets.push({
      id: `${id}::${candidate.folder}`,
      folder: candidate.folder,
      relativePath: path.join(...candidate.segments),
      bytes,
      files,
      safety: candidate.safety || 'safe',
      restoredBy: candidate.restoredBy,
      removed: false,
    })
  }

  if (await checkpoint(state)) return null

  const rest = await measureTree(dir, state, exclude, tuning)
  const targetBytes = targets.reduce((sum, target) => sum + target.bytes, 0)

  let lastModified = new Date()
  try {
    lastModified = (await fsp.stat(dir)).mtime
  } catch {
    /* keep the fallback */
  }

  return {
    id,
    name: path.basename(dir),
    path: dir,
    kind,
    framework: kind === 'node' ? await nodeFramework(dir) : await androidFramework(dir),
    totalBytes: rest.bytes + targetBytes,
    lastModified: lastModified.toISOString(),
    targets,
  }
}

/** Guards deletion: absolute, nested, and named like a rebuildable folder. */
function isRemovable(candidate) {
  if (typeof candidate !== 'string' || !path.isAbsolute(candidate)) return false
  const normalized = path.normalize(candidate)
  if (normalized.split(path.sep).includes('..')) return false
  const segments = normalized.split(path.sep).filter(Boolean)
  if (segments.length < 3) return false
  return REMOVABLE_FOLDERS.has(path.basename(normalized).toLowerCase())
}

function describe(error) {
  if (!error) return 'Unknown error'
  if (error.code === 'EBUSY' || error.code === 'EPERM' || error.code === 'EACCES') {
    return 'In use — close your editor, dev server or Explorer window and try again'
  }
  if (error.code === 'ENOENT') return 'Already gone'
  if (error.code === 'ENOTEMPTY') return 'Files were written into it while deleting'
  return error.message || String(error)
}

/**
 * Deletes a tree by unlinking files in parallel, then removing the directories
 * deepest-first.
 *
 * `fs.rm({recursive:true})` walks and deletes largely one entry at a time. On
 * Windows every unlink goes through the filter driver, so the work is latency-
 * bound and width is what wins: measured on a 19,800-file tree this is about
 * 2.4x faster than `fs.rm`, and far faster than `rd /s /q` or robocopy.
 *
 * @returns the files it removed, and anything it could not
 */
function ignore() {
  /* a path that will not go is reported by the caller, not thrown from here */
}

async function removeTree(target, state, width, onProgress) {
  const directories = []
  const stubborn = []
  let removed = 0

  async function unlinkChunk(paths) {
    const results = await Promise.all(
      paths.map((entry) => fsp.unlink(entry).then(() => null, (error) => ({ path: entry, error }))),
    )
    results.forEach((failure) => {
      if (failure) stubborn.push(failure)
      else removed += 1
    })
    if (onProgress) onProgress(removed)
  }

  async function walk(dir) {
    if (await checkpoint(state)) return

    let entries
    try {
      entries = await fsp.readdir(dir, { withFileTypes: true })
    } catch (error) {
      stubborn.push({ path: dir, error })
      return
    }

    directories.push(dir)
    const files = []
    const subdirectories = []

    for (const entry of entries) {
      const full = path.join(dir, entry.name)
      // A junction or symlink is unlinked, never followed — following one would
      // delete whatever it points at.
      if (entry.isDirectory() && !entry.isSymbolicLink()) subdirectories.push(full)
      else files.push(full)
    }

    for (let index = 0; index < files.length; index += width) {
      if (await checkpoint(state)) return
      await unlinkChunk(files.slice(index, index + width))
    }

    for (let index = 0; index < subdirectories.length; index += 8) {
      if (await checkpoint(state)) return
      await Promise.all(subdirectories.slice(index, index + 8).map(walk))
    }
  }

  await walk(target)

  // Read-only bits (npm and Gradle set them) come back as EPERM. Clear them and
  // have one more go before calling the file locked.
  const retryable = stubborn.filter((entry) => entry.error && (entry.error.code === 'EPERM' || entry.error.code === 'EACCES'))
  if (retryable.length > 0 && !state.cancelled) {
    stubborn.length = 0
    for (let index = 0; index < retryable.length; index += width) {
      const chunk = retryable.slice(index, index + width)
      await Promise.all(chunk.map((entry) => fsp.chmod(entry.path, 0o666).catch(ignore)))
      await unlinkChunk(chunk.map((entry) => entry.path))
    }
  }

  // Deepest first, so a directory is always empty by the time it is removed.
  directories.sort((a, b) => b.split(path.sep).length - a.split(path.sep).length)
  for (const dir of directories) {
    if (state.cancelled) break
    await fsp.rmdir(dir).catch(ignore)
  }

  return { removed, stubborn }
}

/**
 * Delete one target folder and report the bytes actually freed.
 *
 * `known` carries the size and file count from the scan. Without it the folder
 * has to be walked once to measure and again to delete, which doubles the work
 * for a number the scan already knew.
 */
async function removeTarget(target, state, tuning = DEFAULT_TUNING, known = null, onProgress = null) {
  if (!isRemovable(target)) {
    return { ok: false, bytes: 0, files: 0, error: 'Refused: not a recognised rebuildable folder', locked: [] }
  }
  if (!(await isDirectory(target))) {
    return { ok: true, bytes: 0, files: 0, error: null, locked: [] }
  }

  const measured = known && known.bytes > 0 ? known : await measureTree(target, state, null, tuning)
  const width = tuning.deleteBatch || DEFAULT_TUNING.deleteBatch

  const { removed, stubborn } = await removeTree(target, state, width, onProgress)

  if (state.cancelled) {
    const after = await measureTree(target, state, null, tuning)
    return {
      ok: false,
      bytes: Math.max(0, measured.bytes - after.bytes),
      files: removed,
      error: 'Stopped part-way through',
      locked: [],
    }
  }

  if (!fs.existsSync(target)) {
    return { ok: true, bytes: measured.bytes, files: removed, error: null, locked: [] }
  }

  // Something is still there. Report what is left and which paths would not go,
  // so the caller can find out who is holding them.
  const after = await measureTree(target, state, null, tuning)
  const locked = stubborn.slice(0, 12).map((entry) => entry.path)
  const blocking = stubborn.some(
    (entry) => entry.error && ['EPERM', 'EACCES', 'EBUSY', 'ENOTEMPTY'].includes(entry.error.code),
  )

  return {
    ok: false,
    bytes: Math.max(0, measured.bytes - after.bytes),
    files: removed,
    error: blocking ? 'In use by another program' : describe(stubborn[0] && stubborn[0].error),
    locked,
  }
}

module.exports = { findProjects, measureProject, isRemovable, isRootLike, removeTarget, removeTree, measureTree, DEFAULT_TUNING }
