import type { CleanTarget, Project, ProjectKind } from '../types/project';

const MB = 1024 * 1024;
const GB = 1024 * MB;

interface TargetSeed {
  folder: string;
  relativePath?: string;
  bytes: number;
  files: number;
  safety?: CleanTarget['safety'];
  restoredBy: string;
}

interface ProjectSeed {
  name: string;
  kind: ProjectKind;
  framework: string;
  extraBytes: number;
  lastModifiedDaysAgo: number;
  targets: TargetSeed[];
}

const ROOT = 'C:\\Users\\dev\\Projects';

const NPM_INSTALL = 'Restored by `npm install`';
const PNPM_INSTALL = 'Restored by `pnpm install`';
const YARN_INSTALL = 'Restored by `yarn`';
const NEXT_BUILD = 'Rebuilt on next `next build`';
const VITE_BUILD = 'Rebuilt on next `vite build`';
const GRADLE_BUILD = 'Rebuilt on next Gradle sync';

const SEEDS: ProjectSeed[] = [
{
  name: 'acme-dashboard',
  kind: 'node',
  framework: 'Next.js 14',
  extraBytes: 184 * MB,
  lastModifiedDaysAgo: 2,
  targets: [
  { folder: 'node_modules', bytes: 1.42 * GB, files: 148_320, restoredBy: PNPM_INSTALL },
  { folder: '.next', bytes: 612 * MB, files: 9_140, restoredBy: NEXT_BUILD },
  { folder: '.turbo', bytes: 96 * MB, files: 1_204, restoredBy: 'Rebuilt on next Turbo run' }]

},
{
  name: 'orbit-design-system',
  kind: 'node',
  framework: 'Vite + React 18',
  extraBytes: 62 * MB,
  lastModifiedDaysAgo: 9,
  targets: [
  { folder: 'node_modules', bytes: 968 * MB, files: 96_540, restoredBy: PNPM_INSTALL },
  { folder: 'dist', bytes: 74 * MB, files: 620, restoredBy: VITE_BUILD },
  { folder: 'storybook-static', bytes: 138 * MB, files: 1_890, restoredBy: 'Rebuilt by `build-storybook`' }]

},
{
  name: 'pulse-mobile',
  kind: 'node',
  framework: 'React Native 0.74',
  extraBytes: 320 * MB,
  lastModifiedDaysAgo: 21,
  targets: [
  { folder: 'node_modules', bytes: 1.86 * GB, files: 204_770, restoredBy: YARN_INSTALL },
  { folder: 'android/build', relativePath: 'android\\build', bytes: 742 * MB, files: 8_410, restoredBy: GRADLE_BUILD },
  { folder: 'android/.gradle', relativePath: 'android\\.gradle', bytes: 486 * MB, files: 3_260, restoredBy: GRADLE_BUILD }]

},
{
  name: 'fieldkit-android',
  kind: 'android',
  framework: 'Gradle 8.5 · Kotlin',
  extraBytes: 410 * MB,
  lastModifiedDaysAgo: 5,
  targets: [
  { folder: 'build', bytes: 1.24 * GB, files: 14_620, restoredBy: GRADLE_BUILD },
  { folder: 'app/build', relativePath: 'app\\build', bytes: 2.16 * GB, files: 28_940, restoredBy: GRADLE_BUILD },
  { folder: '.gradle', bytes: 1.08 * GB, files: 6_180, restoredBy: GRADLE_BUILD },
  {
    folder: '.cxx',
    bytes: 704 * MB,
    files: 4_020,
    safety: 'caution',
    restoredBy: 'Triggers a full NDK rebuild (slow)'
  }]

},
{
  name: 'lunar-api',
  kind: 'node',
  framework: 'Node 20 · Fastify',
  extraBytes: 48 * MB,
  lastModifiedDaysAgo: 1,
  targets: [
  { folder: 'node_modules', bytes: 512 * MB, files: 48_110, restoredBy: NPM_INSTALL },
  { folder: 'coverage', bytes: 88 * MB, files: 940, restoredBy: 'Regenerated by `npm test`' }]

},
{
  name: 'atlas-storefront',
  kind: 'node',
  framework: 'Remix 2 · Vite',
  extraBytes: 96 * MB,
  lastModifiedDaysAgo: 47,
  targets: [
  { folder: 'node_modules', bytes: 1.12 * GB, files: 121_400, restoredBy: NPM_INSTALL },
  { folder: 'build', bytes: 168 * MB, files: 1_460, restoredBy: 'Rebuilt on next `remix build`' },
  { folder: '.cache', bytes: 212 * MB, files: 2_880, restoredBy: 'Rebuilt automatically on dev start' }]

},
{
  name: 'kotlin-wear-companion',
  kind: 'android',
  framework: 'Gradle 8.2 · Jetpack Compose',
  extraBytes: 172 * MB,
  lastModifiedDaysAgo: 64,
  targets: [
  { folder: 'app/build', relativePath: 'app\\build', bytes: 1.34 * GB, files: 18_220, restoredBy: GRADLE_BUILD },
  { folder: '.gradle', bytes: 620 * MB, files: 3_940, restoredBy: GRADLE_BUILD },
  { folder: 'wear/build', relativePath: 'wear\\build', bytes: 388 * MB, files: 5_120, restoredBy: GRADLE_BUILD }]

},
{
  name: 'nebula-docs',
  kind: 'node',
  framework: 'Astro 4',
  extraBytes: 41 * MB,
  lastModifiedDaysAgo: 12,
  targets: [
  { folder: 'node_modules', bytes: 684 * MB, files: 62_300, restoredBy: PNPM_INSTALL },
  { folder: 'dist', bytes: 54 * MB, files: 720, restoredBy: 'Rebuilt on next `astro build`' }]

},
{
  name: 'legacy-pos-terminal',
  kind: 'android',
  framework: 'Gradle 6.9 · Java',
  extraBytes: 264 * MB,
  lastModifiedDaysAgo: 318,
  targets: [
  { folder: 'app/build', relativePath: 'app\\build', bytes: 940 * MB, files: 11_640, restoredBy: GRADLE_BUILD },
  { folder: '.gradle', bytes: 1.46 * GB, files: 8_220, restoredBy: GRADLE_BUILD },
  { folder: 'buildSrc/build', relativePath: 'buildSrc\\build', bytes: 216 * MB, files: 1_920, restoredBy: GRADLE_BUILD },
  {
    folder: 'captures',
    bytes: 132 * MB,
    files: 84,
    safety: 'caution',
    restoredBy: 'Profiler captures are not regenerated'
  }]

},
{
  name: 'quartz-admin',
  kind: 'node',
  framework: 'Create React App 5',
  extraBytes: 58 * MB,
  lastModifiedDaysAgo: 156,
  targets: [
  { folder: 'node_modules', bytes: 1.31 * GB, files: 176_940, restoredBy: NPM_INSTALL },
  { folder: 'build', bytes: 92 * MB, files: 610, restoredBy: 'Rebuilt on next `npm run build`' }]

},
{
  name: 'signal-worker',
  kind: 'node',
  framework: 'Node 20 · TypeScript',
  extraBytes: 22 * MB,
  lastModifiedDaysAgo: 3,
  targets: [
  { folder: 'node_modules', bytes: 296 * MB, files: 28_640, restoredBy: PNPM_INSTALL },
  { folder: 'dist', bytes: 18 * MB, files: 210, restoredBy: 'Rebuilt on next `tsc -b`' }]

},
{
  name: 'harbor-analytics',
  kind: 'node',
  framework: 'Turborepo · 6 packages',
  extraBytes: 214 * MB,
  lastModifiedDaysAgo: 30,
  targets: [
  { folder: 'node_modules', bytes: 2.24 * GB, files: 268_410, restoredBy: PNPM_INSTALL },
  { folder: '.turbo', bytes: 184 * MB, files: 2_140, restoredBy: 'Rebuilt on next Turbo run' },
  { folder: 'apps/web/.next', relativePath: 'apps\\web\\.next', bytes: 498 * MB, files: 7_320, restoredBy: NEXT_BUILD }]

},
{
  name: 'drone-telemetry',
  kind: 'android',
  framework: 'Gradle 8.4 · NDK',
  extraBytes: 188 * MB,
  lastModifiedDaysAgo: 88,
  targets: [
  { folder: 'app/build', relativePath: 'app\\build', bytes: 806 * MB, files: 9_880, restoredBy: GRADLE_BUILD },
  { folder: '.gradle', bytes: 512 * MB, files: 3_100, restoredBy: GRADLE_BUILD },
  {
    folder: '.cxx',
    bytes: 1.02 * GB,
    files: 6_460,
    safety: 'caution',
    restoredBy: 'Triggers a full NDK rebuild (slow)'
  }]

},
{
  name: 'ember-cli-tools',
  kind: 'node',
  framework: 'Node 18 · CLI',
  extraBytes: 12 * MB,
  lastModifiedDaysAgo: 6,
  targets: []
},
{
  name: 'sentinel-android-lib',
  kind: 'android',
  framework: 'Gradle 8.5 · Library',
  extraBytes: 34 * MB,
  lastModifiedDaysAgo: 14,
  targets: []
}];


function buildProject(seed: ProjectSeed, index: number): Project {
  const id = `p${index + 1}`;
  const targets: CleanTarget[] = seed.targets.map((target) => ({
    id: `${id}::${target.folder}`,
    folder: target.folder,
    relativePath: target.relativePath ?? target.folder,
    bytes: Math.round(target.bytes),
    files: target.files,
    safety: target.safety ?? 'safe',
    restoredBy: target.restoredBy,
    removed: false
  }));
  const targetBytes = targets.reduce((sum, target) => sum + target.bytes, 0);
  const lastModified = new Date(Date.now() - seed.lastModifiedDaysAgo * 24 * 60 * 60 * 1000).toISOString();

  return {
    id,
    name: seed.name,
    path: `${ROOT}\\${seed.name}`,
    kind: seed.kind,
    framework: seed.framework,
    totalBytes: Math.round(targetBytes + seed.extraBytes),
    lastModified,
    targets
  };
}

export const mockProjects: Project[] = SEEDS.map(buildProject);

export const mockRoot = ROOT;

export const recentRoots: string[] = [
'C:\\Users\\dev\\Projects',
'D:\\work\\clients',
'C:\\Users\\dev\\AndroidStudioProjects'];